project:
  type: website
  output-dir: docs
  
website:
  title: "Blog"
  navbar:
    right:
      - about.qmd
      - icon: globe
        href: https://hrayrmuradyan.github.io/docs/index.html
      - icon: youtube
        href: https://www.youtube.com/@EasyAIForAll
      - icon: linkedin
        href: https://www.linkedin.com/in/hrayr-muradyan/
      - icon: github
        href: https://github.com/HrayrMuradyan
format:
  html:
    theme: cosmo
    css: styles.css



